In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spam_assassin.csv')

In [3]:
def clean_email(email):
    clean_email = []
    for i in email:
        if not i.isalnum():
            i = i.replace(i, ' ')
            clean_email.append(i)
        else:
            i = i.lower()
            clean_email.append(i)
    clean_email = "".join(clean_email)
    return clean_email

In [4]:
def convert_email_in_dict(email):
    word_freq = {}
    for word in email.split():
        if word in word_freq:
            word_freq[word] +=1
        else:
            word_freq[word] = 1
    return word_freq

In [5]:
def words_to_df(word_freq):
    df_word = pd.DataFrame.from_dict(word_freq, orient = 'index').fillna(0)
    df_word = df_word.T
    return df_word

In [6]:
all_dfs = []

for i in range(len(df)):

    # ✅ progress checkpoint
    if i % 100 == 0:
        print(f"Processed {i} emails")

    clean = clean_email(df.iloc[i, 0])
    word_freq = convert_email_in_dict(clean)
    all_dfs.append(word_freq)

final_dfs = pd.DataFrame(all_dfs).fillna(0)

Processed 0 emails
Processed 100 emails
Processed 200 emails
Processed 300 emails
Processed 400 emails
Processed 500 emails
Processed 600 emails
Processed 700 emails
Processed 800 emails
Processed 900 emails
Processed 1000 emails
Processed 1100 emails
Processed 1200 emails
Processed 1300 emails
Processed 1400 emails
Processed 1500 emails
Processed 1600 emails
Processed 1700 emails
Processed 1800 emails
Processed 1900 emails
Processed 2000 emails
Processed 2100 emails
Processed 2200 emails
Processed 2300 emails
Processed 2400 emails
Processed 2500 emails
Processed 2600 emails
Processed 2700 emails
Processed 2800 emails
Processed 2900 emails
Processed 3000 emails
Processed 3100 emails
Processed 3200 emails
Processed 3300 emails
Processed 3400 emails
Processed 3500 emails
Processed 3600 emails
Processed 3700 emails
Processed 3800 emails
Processed 3900 emails
Processed 4000 emails
Processed 4100 emails
Processed 4200 emails
Processed 4300 emails
Processed 4400 emails
Processed 4500 emails


In [7]:
final_dfs

from  ilug  admin  linux    ie   mon   jul   29   11   28  ...  273578  \
0       10  17.0    5.0   16.0  22.0   3.0  11.0  3.0  7.0  1.0  ...     0.0   
1        5   0.0    0.0    0.0   0.0   1.0   0.0  1.0  4.0  0.0  ...     0.0   
2       12   0.0    4.0    0.0   0.0   3.0  12.0  3.0  6.0  1.0  ...     0.0   
3        5   0.0    0.0    0.0   0.0   4.0   0.0  1.0  5.0  0.0  ...     0.0   
4       11  13.0    4.0   16.0  22.0   3.0   0.0  0.0  6.0  0.0  ...     0.0   
...    ...   ...    ...    ...   ...   ...   ...  ...  ...  ...  ...     ...   
5791    12  17.0    4.0   18.0  15.0  10.0  10.0  0.0  2.0  0.0  ...     0.0   
5792    10   0.0    4.0    0.0   0.0   8.0   0.0  0.0  3.0  0.0  ...     0.0   
5793    11   0.0    1.0    0.0   0.0   0.0   8.0  0.0  1.0  0.0  ...     0.0   
5794    21   0.0    5.0    0.0   0.0   0.0   0.0  2.0  4.0  0.0  ...     1.0   
5795     5   0.0    0.0    0.0   0.0   5.0   0.0  0.0  2.0  0.0  ...     0.0   

      disconnecting  273982  274203  274585  8524016f03  g8u81gg21362  \
0               0.0     0.0     0.0     0.0         0.0           0.0   
1               0.0     0.0     0.0     0.0         0.0           0.0   
2               0.0     0.0     0.0     0.0         0.0           0.0   
3               0.0     0.0     0.0     0.0         0.0           0.0   
4               0.0     0.0     0.0     0.0         0.0           0.0   
...             ...     ...     ...     ...         ...           ...   
5791            0.0     0.0     0.0     0.0         0.0           0.0   
5792            0.0     0.0     0.0     0.0         0.0           0.0   
5793            0.0     0.0     0.0     0.0         0.0           0.0   
5794            1.0     1.0     1.0     1.0         0.0           0.0   
5795            0.0     0.0     0.0     0.0         1.0           2.0   

      freeserved  8381146  bulkley  
0            0.0      0.0      0.0  
1            0.0      0.0      0.0  
2            0.0      0.0      0.0  
3            0.0      0.0      0.0  
4            0.0      0.0      0.0  
...          ...      ...      ...  
5791         0.0      0.0      0.0  
5792         0.0      0.0      0.0  
5793         0.0      0.0      0.0  
5794         0.0      0.0      0.0  
5795         1.0      1.0      1.0  

[5796 rows x 130726 columns]

In [8]:
target = df["target"]
final_dfs["Target"] = target
final_dfs["Target"]

0       0
1       1
2       1
3       1
4       0
       ..
5791    0
5792    0
5793    1
5794    0
5795    0
Name: Target, Length: 5796, dtype: int64

In [9]:
X = final_dfs.drop("Target",axis = 1)
y = final_dfs["Target"]

In [10]:
from sklearn.model_selection import StratifiedShuffleSplit
splitter = StratifiedShuffleSplit(n_splits= 1, test_size= 0.2, random_state= 42)

for train_index,test_index in splitter.split(final_dfs,final_dfs['Target']):
    X_train = final_dfs.drop(columns = ["Target"]).iloc[train_index]
    y_train = final_dfs["Target"].iloc[train_index]
    X_test = final_dfs.drop(columns=["Target"]).iloc[test_index]
    y_test = final_dfs["Target"].iloc[test_index]


In [11]:
for train_index_val, test_index_val in splitter.split(X_train,y_train):
    X_train_final = X_train.iloc[train_index_val]
    y_train_final = y_train.iloc[train_index_val]

    X_val = X_train.iloc[test_index_val]
    y_val = y_train.iloc[test_index_val]

In [12]:
print(X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape)

(4636, 130726) (4636,) (928, 130726) (928,) (1160, 130726) (1160,)


<h1>Logistic Regression</h1>

In [13]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [14]:
model.fit(X_train_final,y_train_final)

LogisticRegression()

In [15]:
y_pred = model.predict(X_val)

In [16]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_val,y_pred))
print(confusion_matrix(y_val,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       624
           1       0.98      0.99      0.99       304

    accuracy                           0.99       928
   macro avg       0.99      0.99      0.99       928
weighted avg       0.99      0.99      0.99       928

[[618   6]
 [  3 301]]


In [17]:
y_test_pred = model.predict(X_test)

In [18]:
print(classification_report(y_test,y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       781
           1       0.99      0.99      0.99       379

    accuracy                           0.99      1160
   macro avg       0.99      0.99      0.99      1160
weighted avg       0.99      0.99      0.99      1160

[[777   4]
 [  4 375]]


<h1>Multinomial Naive Bayes</h1>

In [19]:
from sklearn.naive_bayes import MultinomialNB
model_MNB = MultinomialNB()

In [20]:
model_MNB.fit(X_train_final, y_train_final)

MultinomialNB()

In [21]:
y_pred_val_MNB = model_MNB.predict(X_val)

In [22]:
print(classification_report(y_val, y_pred_val_MNB))
print(confusion_matrix(y_val, y_pred_val_MNB))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       624
           1       0.99      0.91      0.95       304

    accuracy                           0.97       928
   macro avg       0.98      0.96      0.97       928
weighted avg       0.97      0.97      0.97       928

[[622   2]
 [ 26 278]]


In [23]:
y_test_MNB = model_MNB.predict(X_test)
print(classification_report(y_test,y_test_MNB))
print(confusion_matrix(y_test, y_test_MNB))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97       781
           1       0.99      0.88      0.93       379

    accuracy                           0.96      1160
   macro avg       0.97      0.94      0.95      1160
weighted avg       0.96      0.96      0.96      1160

[[778   3]
 [ 45 334]]


<h1>Linear Support Vector Classification</h1>

In [24]:
from sklearn.svm import LinearSVC
model_SVC = LinearSVC()

In [25]:
model_SVC.fit(X_train_final, y_train_final)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [26]:
y_pred_val_SVC = model_SVC.predict(X_val)

In [27]:
print(classification_report(y_val, y_pred_val_SVC))
print(confusion_matrix(y_val, y_pred_val_SVC))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       624
           1       0.99      0.99      0.99       304

    accuracy                           0.99       928
   macro avg       0.99      0.99      0.99       928
weighted avg       0.99      0.99      0.99       928

[[621   3]
 [  3 301]]


In [28]:
y_test_SVC = model_SVC.predict(X_test)
print(classification_report(y_test,y_test_SVC))
print(confusion_matrix(y_test, y_test_SVC))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       781
           1       0.99      0.99      0.99       379

    accuracy                           0.99      1160
   macro avg       0.99      0.99      0.99      1160
weighted avg       0.99      0.99      0.99      1160

[[777   4]
 [  5 374]]


<h1>Stochastic Gradient Descent</h1>

In [29]:
from sklearn.linear_model import SGDClassifier
model_SGD = SGDClassifier()

In [30]:
model_SGD.fit(X_train_final, y_train_final)

SGDClassifier()

In [31]:
y_pred_val_SGD = model_SGD.predict(X_val)

In [32]:
print(classification_report(y_val, y_pred_val_SGD))
print(confusion_matrix(y_val, y_pred_val_SGD))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99       624
           1       0.96      0.98      0.97       304

    accuracy                           0.98       928
   macro avg       0.98      0.98      0.98       928
weighted avg       0.98      0.98      0.98       928

[[613  11]
 [  7 297]]


In [33]:
y_test_SGD = model.predict(X_test)
print(classification_report(y_test, y_test_SGD))
print(confusion_matrix(y_test, y_test_SGD))


              precision    recall  f1-score   support

           0       0.99      0.99      0.99       781
           1       0.99      0.99      0.99       379

    accuracy                           0.99      1160
   macro avg       0.99      0.99      0.99      1160
weighted avg       0.99      0.99      0.99      1160

[[777   4]
 [  4 375]]
